# -*- coding: utf-8 -*-
"""Sentence Transformers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tfu5YiQ38MlZKVjHZ5yRGqercKUcPgOp
"""

!pip install Sentence_Transformers

from sentence_transformers import SentenceTransformer,util

#Load the model
model=SentenceTransformer('all-MiniLM-L6-V2')

#Take input from user
text1=input("Enter text 1:")
text2=input("Enter text 2:")

#Convert text to embeddings
embedding1=model.encode(text1)
embedding2=model.encode(text2)

#Calculate similarity
similarity=util.cos_sim(embedding1,embedding2)

#Show result
print("\nsimilarity score:",round(float(similarity),2))

if similarity>0.75:
  print("similarity level:high")
elif similarity>0.4:
  print("similarity level:medium")
else:
  print("similarity level:low")