# -*- coding: utf-8 -*-
"""Torch pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M8guU1SH_DFqKF6REGJG5xTmW3kb7s1K
"""

!pip install transformers torch pandas

from transformers import pipeline
import pandas as pd



#load sentiment analysis model
sentiment=pipeline("sentiment-analysis")

#sample product review(you can change only this text later)
reviews="""the laptab starts quickly and works smoothly for daily tasks
the screen quality is clear and good for watching videos
battery backup is average and needs charging often
the fan makes noise when many apps running
overall,it is a good laptab for students but not for gaming"""

#split review into sentences
sentences = reviews.split("\n") # Changed split delimiter from "." to "\n"

pros = []
cons = []

for s in sentences:
    s = s.strip()
    if s == "":
       continue

    result = sentiment(s)[0]

    if result["label"] == "POSITIVE":
        pros.append(s)
    elif result["label"] == "NEGATIVE":
        cons.append(s)

   #take only 2 pros and 2 cons
pros = pros[:2]
cons = cons[:2]
df = pd.DataFrame({
    "pros":pros,
    "cons":cons
})
df